wordpress:
  build: ./containers/multisite
  environment:
    - WORDPRESS_DB_NAME=multisite
    - WORDPRESS_DB_USER=root
    - WORDPRESS_DB_PASS=root
  ports:
    - 80:80
mysql:
  environment:
    - MYSQL_ROOT_PASSWORD=root
  ports:
    - 3306:3306
