wordpress:
  build: ./containers/multisite
  environment:
    - WORDPRESS_DB_NAME=wordpress
    - WORDPRESS_DB_USER=root
    - WORDPRESS_DB_PASS=root
  ports:
    - 80:80
mysql:
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=wordpress
    - MYSQL_USER=wordpress
    - MYSQL_PASSWORD=wordpress
  ports:
    - 3306:3306
